name: R-CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          Rscript -e 'pkgs <- c("optparse","leaps","boot","readxl","dplyr"); ins <- setdiff(pkgs, rownames(installed.packages())); if (length(ins)) install.packages(ins, repos="https://cloud.r-project.org")'
      - name: Demo run
        run: Rscript scripts/mortgage_stepwise_cv.R --demo
